openapi: 3.0.0
info:
  title: Teams API
  version: 1.0.0

paths:
  /team:
    patch:
      tags:
        - TeamLeaders
      summary: Update a team's details
      operationId: updateTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTeamRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTeamSuccessResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Team not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTeamErrorResponse'

   
components:
  schemas:
    UpdateTeamRequest:
      type: object
      properties:
        team:
          type: object
          properties:
            team_id:
              type: integer
            name:
              type: string
            active:
              type: boolean
            website_link:
              type: string
              format: uri
            desc:
              type: string
            pitching_order:
              type: integer
      example:
        team:
          team_id: 38
          name: "Trimmle M"
          active: true
          website_link: "https://www.youtube.com/watch?v=ocn_2s_Q3n4"
          desc: "Description"
          pitching_order: 1
    UpdateTeamSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          properties:
            team:
              $ref: '#/components/schemas/Team'
      example:
        success: true
        message:
          team:
            id: 93
            name: "Trimmle M"
            desc: "Description"
            active: true
            website_link: "https://www.youtube.com/watch?v=ocn_2s_Q3n4"
            organizer_id: 6
            created_at: "2024-03-20T12:03:02.490Z"
            updated_at: "2024-06-16T07:04:23.176Z"
            event_id: 38
            total_score: null
            pitching_order: 1
    UpdateTeamErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          properties:
            error:
              type: string
      example:
        success: false
        message:
          error: "Team does not exist in the database"
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        desc:
          type: string
          nullable: true
        active:
          type: boolean
        website_link:
          type: string
          nullable: true
        organizer_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        event_id:
          type: integer
        total_score:
          type: number
          format: float
          nullable: true
        pitching_order:
          type: integer
          nullable: true

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        errors:
          type: array
          items:
            type: string   